// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'grid': string;
  'info': string;
  'releaseLink': string;
  'resolution': string;
  'selectButton': string;
  'sourceBadge': string;
  'thumbnail': string;
}
export const cssExports: CssExports;
export default cssExports;
